builds:
  - id: linux-amd64-build
    binary: bigmoji
    goos:
      - linux
    goarch:
      - amd64
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    env: &build-env
      - CGO_ENABLED=0
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.Version={{.Version}}

  - id: linux-arm64-build
    binary: bigmoji
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

  - id: darwin-build
    binary: bigmoji
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

universal_binaries:
- id: darwin-build
- replace: true

archives:
  - id: default-archive
    builds:
      - linux-amd64-build
      - linux-arm64-build
      - darwin-build
    replacements:
      darwin: macOS
      amd64: x86_64
      all: universal

brews:
  - name: bigmoji

    tap:
      owner: joepurdy
      name: homebrew-tap

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/joepurdy/bigmoji/"

    description: "A helper utility for slicing PNGs into 4x4 grids for Slack Bigmojis."

    # SPDX identifier of the license.
    license: "MIT"

    test: |
      system "#{bin}/bigmoji --version"