# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64-build
    binary: bigmoji
    goos:
      - linux
    goarch:
      - amd64
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    env: &build-env
      - CGO_ENABLED=0
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.Version={{.Version}}
    ignore:
      - goos: windows
      - goos: darwin

  - id: linux-arm64-build
    binary: bigmoji
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags
    ignore:
      - goos: windows
      - goos: darwin

  - id: darwin-build
    binary: bigmoji
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags
    ignore:
      - goos: windows
      - goos: linux

universal_binaries:
- id: darwin-build
  replace: true

archives:
  - id: default-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    strip_binary_directory: true
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: bigmoji
    repository:
      owner: joepurdy
      name: homebrew-tap
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/joepurdy/bigmoji/"
    description: "A helper utility for slicing PNGs into 4x4 grids for Slack Bigmojis."
    license: "MIT"
    test: |
      system "#{bin}/bigmoji --version"
    install: |
      bin.install "bigmoji"
    caveats: |
      You can now use bigmoji to create Slack Bigmojis!